version: '3.4'

services:

  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    volumes:
      - /C/MVCCoreDocker/vol/mssql-server-linux-data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word1
    ports:
      - 1433:1433
    

  mvccoredocker:
    image: ${DOCKER_REGISTRY-}mvccoredocker
    build:
      context: .
      dockerfile: MVCCoreDocker/Dockerfile
    
  


volumes:
  mssql-server-linux-data:
   